
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: bestuser
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9765